<a href="https://colab.research.google.com/github/SimranThakur0/ML_ASSIGNMENTS/blob/main/exam_practice_daf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	To Compute the Eigen values of a matrix, Compute the multiplicative inverse of a matrix

In [ ]:
import numpy as np

In [ ]:
def comp_eig(matrix):
    value,vectors = np.linalg.eig(matrix)
    return value
def comp_inverse(matrix):
    try:
        np.linalg.inv(matrix)
    except np.linalg.LinAlgError:
        return None

matrix = np.array([[1,2,3],[2,4,5],[5,6,7]])
eigenvalues = comp_eig(matrix)
print("Eigenvalues: ", eigenvalues)

inverse = comp_inverse(matrix)
if inverse is not None:
    print("INVERSE: ", inverse)

else:
    print("Matrix is not invertible")





Eigenvalues:  [12.75917896 -1.05604197  0.29686301]
Matrix is not invertible


2.	To write a python programming to find area of Square and area of
Triangle using method overloading  


In [ ]:
class Area:
    def calculate_area(self, *args):
        if len(args) == 1:  # If only one argument is provided, it's a square
            side = args[0]
            area = side * side
            return area
        elif len(args) == 2:  # If two arguments are provided, it's a triangle
            base, height = args
            area = 0.5 * base * height
            return area
        else:
            raise ValueError("Invalid number of arguments")

# Example usage:
geometry = Area()

# Calculate the area of a square with a side length of 5
square_area = geometry.calculate_area(5)
print("Area of Square:", square_area)

# Calculate the area of a triangle with a base of 4 and a height of 3
triangle_area = geometry.calculate_area(4, 3)
print("Area of Triangle:", triangle_area)


Area of Square: 25
Area of Triangle: 6.0


1.	To Design a Python Script to determine the time difference between two
given times in HH:MM:SS format.( 0 <= HH <= 23, 0 <= MM <= 59, 0<= SS <= 59).


In [ ]:
from datetime import datetime
d1=input("Enter date as yyyy:mm:dd:")
d2=input("Enter date as yyyy:mm:dd:")
d3=datetime.strptime(d1,"%Y:%m:%d").date()
d4=datetime.strptime(d2,"%Y:%m:%d").date()
diff=d4-d3
print("The differnce between the days is:",diff)

Enter date as yyyy:mm:dd: 2023:05:23
Enter date as yyyy:mm:dd: 2002:05:23


The differnce between the days is: -7670 days, 0:00:00


2.	Area of Circle and square using multilevel Inheritance

In [ ]:
import math

# Base class representing a shape
class Shape:
    def area(self):
        pass

# Subclass representing a square
class Square(Shape):
    def __init__(self, side):
        self.side = side

    def area(self):
        return self.side * self.side

# Subclass representing a circle
class Circle(Square):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius ** 2

# Example usage
square = Square(5)
circle = Circle(3)

print(f"Area of Square: {square.area()}")
print(f"Area of Circle: {circle.area()}")


Area of Square: 25
Area of Circle: 28.274333882308138


1.	Python to print the various Date Time formats. a) Current  date and time b) Current year c) Month of year d) Week number of the year e) Weekday of the week f) Day of year g) Day of the month h) Dayof week

In [ ]:
import datetime

# a) Current date and time
current_datetime = datetime.datetime.now()
print("a) Current date and time:", current_datetime)

# b) Current year
current_year = current_datetime.year
print("b) Current year:", current_year)

# c) Month of the year
current_month = current_datetime.strftime("%B")
print("c) Month of the year:", current_month)

# d) Week number of the year
week_number = current_datetime.strftime("%U")
print("d) Week number of the year:", week_number)

# e) Weekday of the week (0 = Monday, 6 = Sunday)
weekday = current_datetime.strftime("%A")
print("e) Weekday of the week:", weekday)

# f) Day of the year
day_of_year = current_datetime.timetuple().tm_yday
print("f) Day of the year:", day_of_year)

# g) Day of the month
day_of_month = current_datetime.day
print("g) Day of the month:", day_of_month)

# h) Day of the week (0 = Monday, 6 = Sunday)
day_of_week = current_datetime.weekday()
print("h) Day of the week:", day_of_week)


a) Current date and time: 2023-11-08 11:21:05.634134
b) Current year: 2023
c) Month of the year: November
d) Week number of the year: 45
e) Weekday of the week: Wednesday
f) Day of the year: 312
g) Day of the month: 8
h) Day of the week: 2


2.	Program to Check a Number is Spy number or No

In [ ]:
def is_spy_number(number):
    # Convert the number to a string to iterate over its digits
    number_str = str(number)

    # Calculate the sum and product of the digits
    digit_sum = 0
    digit_product = 1

    for digit in number_str:
        digit_int = int(digit)
        digit_sum += digit_int
        digit_product *= digit_int

    # Check if it's a Spy number
    return digit_sum == digit_product

# Input number to check
num = int(input("Enter a number to check if it's a Spy number: "))

if is_spy_number(num):
    print(f"{num} is a Spy number.")
else:
    print(f"{num} is not a Spy number.")


Enter a number to check if it's a Spy number:  7878


7878 is not a Spy number.


1.	Addition, Subtraction and multiplication using multilevel
2.	To write a python program to concatenate the dataframes with twodifferent objects.


In [ ]:
class Operation:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def addition(self):
        return self.a + self.b

    def subtraction(self):
        return self.a - self.b

class Multiplication(Operation):
    def multiplication(self):
        return self.a * self.b

class Calculator(Multiplication):
    def calculate(self):
        result_add = self.addition()
        result_sub = self.subtraction()
        result_mul = self.multiplication()
        return result_add, result_sub, result_mul

# Example usage
a = 10
b = 5

calc = Calculator(a, b)
addition_result, subtraction_result, multiplication_result = calc.calculate()

print(f"Addition: {a} + {b} = {addition_result}")
print(f"Subtraction: {a} - {b} = {subtraction_result}")
print(f"Multiplication: {a} * {b} = {multiplication_result}")


Addition: 10 + 5 = 15
Subtraction: 10 - 5 = 5
Multiplication: 10 * 5 = 50


In [ ]:
import pandas as pd

# Sample data
data1 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
data2 = {'C': ['x', 'y', 'z'], 'D': ['p', 'q', 'r']}

# Create dataframes from the sample data
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Concatenate the dataframes vertically
result_df = pd.concat([df1, df2], axis=0)

print("Concatenated DataFrame:")
print(result_df)


Concatenated DataFrame:
     A    B    C    D
0  1.0  4.0  NaN  NaN
1  2.0  5.0  NaN  NaN
2  3.0  6.0  NaN  NaN
0  NaN  NaN    x    p
1  NaN  NaN    y    q
2  NaN  NaN    z    r


1.	Python program to add 5 seconds with the current time.
2.	To Create multi-dimensional arrays and find its shape and dimension


In [ ]:
import datetime

# Get the current time
current_time = datetime.datetime.now()

# Add 5 seconds to the current time
new_time = current_time + datetime.timedelta(seconds=5)

print("Current Time:", current_time)
print("Current Time + 5 seconds:", new_time)


Current Time: 2023-11-08 11:24:15.614455
Current Time + 5 seconds: 2023-11-08 11:24:20.614455


In [ ]:
import numpy as np

# Create a 2D array
multi_dim_array = np.array([[1, 2, 3], [4, 5, 6]])

# Find the shape and dimensions
shape = multi_dim_array.shape
dimensions = multi_dim_array.ndim

print("2D Array:")
print(multi_dim_array)
print("Shape:", shape)
print("Dimensions:", dimensions)


2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


1.	To Compute the rank of a matrix & determinant of an array
2.	Write a python Program to print all Twin Primes less than N.


In [ ]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("Matrix:")
print(matrix)
print("Rank of the matrix:", rank)
print("Determinant of the matrix:", determinant)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2
Determinant of the matrix: 0.0


In [ ]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def find_twin_primes(N):
    twin_primes = []
    for num in range(2, N - 1):
        if is_prime(num) and is_prime(num + 2):
            twin_primes.append((num, num + 2))
    return twin_primes

N = int(input("Enter a number (N): "))
twin_prime_pairs = find_twin_primes(N)

print(f"Twin Primes less than {N}:")
for pair in twin_prime_pairs:
    print(pair)


Enter a number (N):  78


Twin Primes less than 78:
(3, 5)
(5, 7)
(11, 13)
(17, 19)
(29, 31)
(41, 43)
(59, 61)
(71, 73)



1.	Area of Circle and square using multilevel Inheritance
2.	to determine the time difference between twogiven times in HH:MM:SS format.( 0 <= HH <= 23, 0 <= MM <= 59, 0<= SS <= 59)


In [ ]:
import math

# Base class for shape
class Shape:
    def __init__(self):
        pass

# Subclass for square
class Square(Shape):
    def __init__(self, side):
        super().__init__()
        self.side = side

    def calculate_area(self):
        return self.side ** 2

# Subclass for circle
class Circle(Shape):
    def __init__(self, radius):
        super().__init__()
        self.radius = radius

    def calculate_area(self):
        return math.pi * self.radius ** 2

# Example usage for calculating areas
square = Square(5)
circle = Circle(3)

print(f"Area of Square: {square.calculate_area()}")
print(f"Area of Circle: {circle.calculate_area()}")

# Example usage for determining time difference
time1 = "12:30:45"
time2 = "14:45:30"

time_diff = time_difference(time1, time2)
print(f"Time difference: {time_diff}")


Area of Square: 25
Area of Circle: 28.274333882308138
Time difference: 02:14:45


In [ ]:
def time_difference(time1, time2):
    try:
        h1, m1, s1 = map(int, time1.split(':'))
        h2, m2, s2 = map(int, time2.split(':'))

        total_seconds1 = h1 * 3600 + m1 * 60 + s1
        total_seconds2 = h2 * 3600 + m2 * 60 + s2

        difference_seconds = abs(total_seconds1 - total_seconds2)

        hours = difference_seconds // 3600
        minutes = (difference_seconds % 3600) // 60
        seconds = difference_seconds % 60

        return f"{hours:02d}:{minutes:02d}:{seconds:02d}"
    except ValueError:
        return "Invalid time format. Please use HH:MM:SS format."


1.	Addition, Subtraction and multiplication using  multiple inheritance.
2.	To Compute the rank of a matrix & determinant of an array



1	To write a python Programming to find Area of Rectangle Hierarchical Inheritance.
2	To Use statistical functions on array - Min, Max, Mean, Median andStandard Deviation.


In [ ]:
class Shape:
    def __init__(self, length, width):
        self.length = length
        self.width = width

class Rectangle(Shape):
    def calculate_area(self):
        return self.length * self.width

class Square(Shape):
    def calculate_area(self):
        return self.length * self.width

# Example usage
length = 5
width = 4

rectangle = Rectangle(length, width)
square = Square(length, width)

print(f"Area of Rectangle: {rectangle.calculate_area()}")
print(f"Area of Square: {square.calculate_area()}")


Area of Rectangle: 20
Area of Square: 20


In [ ]:
import numpy as np

# Sample array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Minimum value
min_value = np.min(data)

# Maximum value
max_value = np.max(data)

# Mean (average) value
mean_value = np.mean(data)

# Median value
median_value = np.median(data)

# Standard deviation
std_deviation = np.std(data)

print("Data Array:", data)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("Mean (Average) Value:", mean_value)
print("Median Value:", median_value)
print("Standard Deviation:", std_deviation)


Data Array: [ 1  2  3  4  5  6  7  8  9 10]
Minimum Value: 1
Maximum Value: 10
Mean (Average) Value: 5.5
Median Value: 5.5
Standard Deviation: 2.8722813232690143


1.	To Reshape and flatten data in the array
2.	write a python program to find sum of the two numbers and productof the three numbers using method overloading.


In [ ]:
import numpy as np

# Sample data
data = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape the data to a different shape
reshaped_data = data.reshape(3, 2)

# Flatten the data
flattened_data = data.flatten()

print("Original Data:")
print(data)

print("\nReshaped Data:")
print(reshaped_data)

print("\nFlattened Data:")
print(flattened_data)


Original Data:
[[1 2 3]
 [4 5 6]]

Reshaped Data:
[[1 2]
 [3 4]
 [5 6]]

Flattened Data:
[1 2 3 4 5 6]


In [ ]:
def calculate_result(a, b=None, c=None):
    if c is not None:
        return a * b * c  # Product of three numbers
    elif b is not None:
        return a + b  # Sum of two numbers
    else:
        return a

# Example usage
result1 = calculate_result(2, 3)
result2 = calculate_result(2, 3, 4)

print("Sum of two numbers:", result1)
print("Product of three numbers:", result2)


Sum of two numbers: 5
Product of three numbers: 24


1.	To write a basic array of operations on single array to add x to each
element of array and subtract y from each element of array Using Numpy
2.	To write a python program to find Pandas Math Functions for Data
Analysis. mean( ), sum ( ), median ( ), min ( ), max ( ), value_counts( ) and describe() function.


In [ ]:
import numpy as np

# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Define values to add and subtract
x = 10
y = 2

# Add x to each element of the array
result_add = arr + x

# Subtract y from each element of the array
result_subtract = arr - y

print("Original Array:", arr)
print("Array after adding", x, "to each element:", result_add)
print("Array after subtracting", y, "from each element:", result_subtract)


Original Array: [1 2 3 4 5]
Array after adding 10 to each element: [11 12 13 14 15]
Array after subtracting 2 from each element: [-1  0  1  2  3]


In [ ]:
import pandas as pd

# Sample data
data = {
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}

# Create a Pandas DataFrame
df = pd.DataFrame(data)

# Pandas math functions
mean = df.mean()
sum_value = df.sum()
median = df.median()
min_value = df.min()
max_value = df.max()
value_counts = df['Age'].value_counts()
description = df.describe()

print("DataFrame:")
print(df)

print("\nMean:")
print(mean)

print("\nSum:")
print(sum_value)

print("\nMedian:")
print(median)

print("\nMinimum:")
print(min_value)

print("\nMaximum:")
print(max_value)

print("\nValue Counts (Age):")
print(value_counts)

print("\nDescription:")
print(description)


DataFrame:
   Age  Salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000
4   45   90000

Mean:
Age          35.0
Salary    70000.0
dtype: float64

Sum:
Age          175
Salary    350000
dtype: int64

Median:
Age          35.0
Salary    70000.0
dtype: float64

Minimum:
Age          25
Salary    50000
dtype: int64

Maximum:
Age          45
Salary    90000
dtype: int64

Value Counts (Age):
25    1
30    1
35    1
40    1
45    1
Name: Age, dtype: int64

Description:
             Age        Salary
count   5.000000      5.000000
mean   35.000000  70000.000000
std     7.905694  15811.388301
min    25.000000  50000.000000
25%    30.000000  60000.000000
50%    35.000000  70000.000000
75%    40.000000  80000.000000
max    45.000000  90000.000000


In [ ]:
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num*0.5)):
        if num % i == 0:
            return False
    return True

def twin_prime(num):



num = int(input("enter a number: "))
res = is_prime(num)
print(res)

enter a number:  7


True
